### Site metadata

# Don't make the title longer than this, otherwise it gets covered in mobile view.
title: Liblung's Beta Blog
description: Cuck Content 4 U

email:
twitter_username:
github_username: liblung
rss: RSS

### Build settings

url: https://liblung.github.io
baseurl: /Hydra

permalink: pretty

remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

collections:
  tools:
    output: true
  languages:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: page

exclude:
  - docs/
  - vendor/
  - Gemfile # Gemfile.lock is implied because of how matching works.
  - LICENSE
  - Makefile
  - sample*.png

liquid:
  error_mode: strict

strict_front_matter: true
